interface Props {
  variant?: 'default' | 'destructive' | 'secondary';
  size?: 'default' | 'lg' | 'sm';
  children?: React.ReactNode;
}

/**
 * Generated by Anima
 */
export function Button({
  variant = 'default',
  size = 'default',
  children,
}: Props) {
  return (
    <button
      className={`all-[unset] relative box-border inline-flex items-center justify-center gap-2.5 overflow-hidden rounded-md ${
        size === 'default'
          ? 'px-4 py-0'
          : size === 'lg'
            ? 'px-6 py-0'
            : 'px-3 py-0'
      } ${size === 'default' ? 'h-10' : size === 'lg' ? 'h-11' : 'h-[30px]'} ${
        variant === 'secondary'
          ? 'bg-[#eff3f4]'
          : variant === 'destructive'
            ? 'bg-[#f53855]'
            : 'bg-[#276aff]'
      }`}
    >
      {children}
    </button>
  );
}
